const types = {
	UI_SHOW_ADD_ITEM: '[UI] Show the add item sidebar',
	UI_HIDE_ADD_ITEM: '[UI] Hide the add item sidebar',
	UI_SHOW_SIDEBAR_RIGHT: '[UI] Show the sidebar right in small screens',
	UI_HIDE_SIDEBAR_RIGHT: '[UI] Hide the sidebar right in small screens',
	UI_TOGGLE_SIDEBAR_RIGHT: '[UI] Toggle the sidebar right in small screens',
	UI_SHOW_ITEM_INFO: '[UI] Show the item info sidebar',
	UI_HIDE_ITEM_INFO: '[UI] Hide the item info sidebar',
	UI_OPEN_DIALOG: '[UI] Open dialog',
	UI_CLOSE_DIALOG: '[UI] Close dialog',
	UI_IS_LOADING: '[UI] Set the loading state to true',
	UI_IS_NOT_LOADING: '[UI] Set the loading state to false',
	AUTH_START_SIGNUP: '[AUTH] Start signup',
	AUTH_SIGNUP: '[AUTH] Signup',
	AUTH_START_SIGNIN: '[AUTH] Start signin',
	AUTH_SIGNIN: '[AUTH] Signin',
	AUTH_LOGOUT: '[AUTH] Logout',
	AUTH_CHECKING_FINISH: '[AUTH] Checking for an authenticated user finish',
	SHOPPING_SAVE_CATEGORIES: '[SHOPPING] Save the user categories',
	SHOPPING_ADD_CATEGORY: '[SHOPPING] Add a new category',
	SHOPPING_SAVE_ITEMS: '[SHOPPING] Save the user items',
	SHOPPING_ADD_ITEM: '[SHOPPING] add a new item',
	SHOPPING_SHOW_ITEM: '[SHOPPING] Show the info of an item',
	SHOPPING_HIDE_ITEM: '[SHOPPING] Hide the info of an item',
	SHOPPING_UPDATE_ITEM: '[SHOPPING] Update an item',
	SHOPPING_DELETE_ITEM: '[SHOPPING] Delete an item',
	CART_SET_LOADING: '[CART] Set the cart loading state',
	CART_GET: '[CART] Get the current user cart',
	CART_ADD_ITEM: '[CART] Add an item to cart',
};

export default types;
